version: '2'
services:
  openfoodfactsbatchloader-app:
    image: pluralsightopenfoodfactsbatchjob
    environment:
      - _JAVA_OPTIONS=-Xmx2048m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pluralsightopenfoodfactsbatchjob-postgresql:5432/PluralsightOpenFoodFactsBatchJob
      - APP_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  openfoodfactsbatchloader-postgresql:
    extends:
      file: postgresql.yml
      service: pluralsightopenfoodfactsbatchjob-postgresql
